// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4FgPaoHgTvCKWRmqmsKwpD2wRg8K2D54',
    appId: '1:652698119526:web:82303469839a8afe53eca7',
    messagingSenderId: '652698119526',
    projectId: 'practice-ecommerce-89894',
    authDomain: 'practice-ecommerce-89894.firebaseapp.com',
    storageBucket: 'practice-ecommerce-89894.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABX19wMqpdCZSoGvPrUd-t0RWFLu68nC8',
    appId: '1:652698119526:android:6db90e57e9e15a9853eca7',
    messagingSenderId: '652698119526',
    projectId: 'practice-ecommerce-89894',
    storageBucket: 'practice-ecommerce-89894.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD43JNKAZYWFVcqIpzAcqxZgnlYcWA0FaA',
    appId: '1:652698119526:ios:8096fbadfad2b29053eca7',
    messagingSenderId: '652698119526',
    projectId: 'practice-ecommerce-89894',
    storageBucket: 'practice-ecommerce-89894.firebasestorage.app',
    iosBundleId: 'com.example.practiceEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD43JNKAZYWFVcqIpzAcqxZgnlYcWA0FaA',
    appId: '1:652698119526:ios:8096fbadfad2b29053eca7',
    messagingSenderId: '652698119526',
    projectId: 'practice-ecommerce-89894',
    storageBucket: 'practice-ecommerce-89894.firebasestorage.app',
    iosBundleId: 'com.example.practiceEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4FgPaoHgTvCKWRmqmsKwpD2wRg8K2D54',
    appId: '1:652698119526:web:473e3aa82ac00ada53eca7',
    messagingSenderId: '652698119526',
    projectId: 'practice-ecommerce-89894',
    authDomain: 'practice-ecommerce-89894.firebaseapp.com',
    storageBucket: 'practice-ecommerce-89894.firebasestorage.app',
  );
}
