// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtkEYOj8ncZyc2dwt7lV93cYWzPJRegnc',
    appId: '1:1049212809961:web:522e10e2a462b29c2af678',
    messagingSenderId: '1049212809961',
    projectId: 'practice-ecommerce-69290',
    authDomain: 'practice-ecommerce-69290.firebaseapp.com',
    storageBucket: 'practice-ecommerce-69290.firebasestorage.app',
    measurementId: 'G-FRZVMEQMKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2EOAbbmhyR94893qY6vIXA8FrnT4bS48',
    appId: '1:1049212809961:android:9053ea84fdf8af262af678',
    messagingSenderId: '1049212809961',
    projectId: 'practice-ecommerce-69290',
    storageBucket: 'practice-ecommerce-69290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjMknZ-nj_0e66OSvjnlO05OGmfhtij4s',
    appId: '1:1049212809961:ios:d6dc0a7c4789cf082af678',
    messagingSenderId: '1049212809961',
    projectId: 'practice-ecommerce-69290',
    storageBucket: 'practice-ecommerce-69290.firebasestorage.app',
    iosBundleId: 'com.example.practiceEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjMknZ-nj_0e66OSvjnlO05OGmfhtij4s',
    appId: '1:1049212809961:ios:d6dc0a7c4789cf082af678',
    messagingSenderId: '1049212809961',
    projectId: 'practice-ecommerce-69290',
    storageBucket: 'practice-ecommerce-69290.firebasestorage.app',
    iosBundleId: 'com.example.practiceEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtkEYOj8ncZyc2dwt7lV93cYWzPJRegnc',
    appId: '1:1049212809961:web:bdb124d39491847f2af678',
    messagingSenderId: '1049212809961',
    projectId: 'practice-ecommerce-69290',
    authDomain: 'practice-ecommerce-69290.firebaseapp.com',
    storageBucket: 'practice-ecommerce-69290.firebasestorage.app',
    measurementId: 'G-489JF2EMK0',
  );
}
